### ISSUE TITLE
Import express-gateway to jx

### ISSUE THREAD

**Issue by awaddell** [cloudsmartio/k8s-infra#5]
Tasks

- [ ] Add Redis as a scalable container service
- [ ] Update Helm or buildpacks to support Redis service
- [ ] Ensure durability of Redis data
